M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu20.04.1} date Tue 18 Jul 2023 05:21:32 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-18T17:21:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
%
G90
G05
T1
X4.9031Y-3.8071
X4.9031Y-4.0669
T2
X4.9803Y-4.6024
X5.8803Y-2.6087
X5.9803Y-2.6087
T0
M30
